### ISSUE TITLE
Error generating voucher code on the register.

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everpsvoucheronsubscribe#1]
On completion of registration it generates the following error:

`Fatal error: Uncaught Error: Call to undefined method Configuration::getInt() in /usr/local/lsws/Example/html/ps80/modules/everpsvoucheronsubscribe/everpsvoucheronsubscribe.php:548 `

PS 8.0.4 & PHP 8.1.19 On Apache server for test.

Many thanks for all.

**Comment by CySSoO** [comment]
Hello
Could you try with this release ?
https://github.com/TeamEver/everpsvoucheronsubscribe/releases/tag/V3.1.2
Best regards

**Comment by Luifer-dnk** [comment]
Yes !!!

Now working...

Many thanks.
